inventory_list/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, get_product_json, add_product_ajax
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_product
from main.views import delete_product
from main.views import decrement_product
from main.views import increment_product
from main.views import create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-product/<int:id>', delete_product, name='delete_product'),
    path('decrement-product/<int:id>', decrement_product, name='decrement_product'),
    path('increment-product/<int:id>', increment_product, name='increment_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "price", "description"]

main/views.py
from django.shortcuts import render
import datetime
from django.http import HttpResponseRedirect,HttpResponseNotFound
from django.urls import reverse
from main.forms import ProductForm
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    if request.method == 'POST':
        if 'increment' in request.POST:
            product_id = request.POST.get('increment')
            product = products.get(id=product_id)
            product.amount += 1
            product.save()
            return HttpResponseRedirect(reverse('main:show_main'))
        elif 'decrement' in request.POST:
            product_id = request.POST.get('decrement')
           
            return HttpResponseRedirect(reverse('main:show_main'))
        elif 'delete' in request.POST:
            product_id = request.POST.get('delete')
            

    counter = products.count()

    context = {
        'app_name':'Inventory List',
        'name': request.user.username,
        'class': 'PBP KKI',
        'products': products,
        'counter' : counter,
        'last_login': request.COOKIES.get('last_login', ''),
            }

    return render(request, 'main.html', context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product by ID
    product = Product.objects.get(pk = id)

    # Set product as instance of form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Save the form and return to home page
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, 'edit_product.html', context)

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        dateAdded = request.POST.get("date_added")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, amount = amount, date_added = dateAdded,price=price, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrement_product(request, id):
    product = Product.objects.get(id = id)
    product.amount -= 1
    product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def increment_product(request, id):
    product = Product.objects.get(id = id)
    product.amount += 1
    product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card" style="max-width: 80%; padding: 20px;"> <!-- Card with a max-width of 80% of viewport and increased padding -->
        <div class="card-body">
            <h1 class="card-title text-center">Add New Product</h1>
            <form method="POST">
                {% csrf_token %}
                <table class="mx-auto"> <!-- Centering the table within the card -->
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Add Product"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
<style>

</style>

{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
    <!-- Make sure to include Bootstrap's CSS if not already in 'base.html' -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
{% endblock meta %}

{% block content %}

<div class="container h-100">
    <div class="row justify-content-center h-100">
        <div class="col-6 align-self-center">
            <div class="card">
                <div class="card-body">

                    <h1 class="text-center">Inventory List</h1>

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" id="username" name="username" placeholder="Username" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" id="password" name="password" placeholder="Password" class="form-control">
                        </div>

                        <div class="text-center">
                            <input class="btn btn-primary login_btn" type="submit" value="Login">
                        </div>
                    </form>

                    {% if messages %}
                        <ul class="mt-3">
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}     

                    <p class="text-center mt-3">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: bisque;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <h2>Inventory List Page</h2>
        </a>

        <span class="navbar-text">
            <h3>Welcome, {{ name }}</h3>
            <span>{{ class }}</span>
        </span>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button> 
            </form>
        </div>
    </div>
</nav>

<style>
    .space-below-navbar {
        margin-top: 50px;
    }
</style>

<div class="container space-below-navbar">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th>Description</th>
                        <th>Date Added</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>{{product.name}}</td>
                        <td>
                            <div class="amount-box">
                                <a href="{% url 'main:decrement_product' product.id %}">
                                    <button class="btn btn-primary btn-sm">-</button>
                                </a>
                                <span class="amount-value">{{product.amount}}</span>
                                <a href="{% url 'main:increment_product' product.id %}">
                                    <button class="btn btn-primary btn-sm">+</button>
                                </a>
                            </div>
                        </td>
                        <td>{{product.price}}</td>
                        <td>{{product.description}}</td>
                        <td>{{product.date_added}}</td>
                        <td>
                            <a href="edit-product/{{ product.id }}">
                                <button type="submit" class="btn btn-dark">Edit Product</button>
                            </a>
                            <a href="delete-product/{{ product.id }}">
                                <button class="btn btn-dark">Delete Product</button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<table id="product_table"></table>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>

<style>
    .space-below-table {
        margin-bottom: 50px;
    }
</style>

<p>You have saved {{counter}} items in this application</p>

<style>
    .btn-standard {
        width: 200px;
        height: 50px;
        display: inline-block;
        text-align: center;
        vertical-align: middle;
        padding: 10px 20px;
    }

    table td,
    table th {
        text-align: center;
        padding: 10px 5px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    table,
    th,
    td {
        border: 1px solid black;
    }

    .amount-value {
        margin: 0 10px;
    }

    .table.table-bordered tbody tr:last-child {
        background-color: lightgray;
        color: black;
    }
</style>

<h5>Last login session: {{ last_login }}</h5>

<a href="{% url 'main:create_product' %}">
    <button class="btn btn-primary" type="button">
        Add New Product
    </button>
</a>


<a href="{% url 'main:logout' %}">
    <button class="btn btn-primary" type="button">
        Logout
    </button>
</a>


<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }
    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = `<tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Description</th>
            <th>Date Added</th>
        </tr>`
        products.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.name}</td>
            <td>${item.fields.amount}</td>
            <td>${item.fields.price}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.date_added}</td>
        </tr>` 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct

</script>

{% endblock content %}

main/templates/register.html
<style>

</style>

{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
    <!-- Make sure to include Bootstrap's CSS if not already in 'base.html' -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
{% endblock meta %}

{% block content %}

<div class="container h-100">
    <div class="row justify-content-center h-100">
        <!-- Adjusting the column width here -->
        <div class="col-8 align-self-center">
            <div class="card">
                <!-- Adding some custom padding inside the card for more spacing -->
                <div class="card-body py-5 px-4">

                    <div class="login">

                        <h1>Register</h1>

                        <form method="POST">
                            {% csrf_token %}
                            <table>
                                {{ form.as_table }}
                                <tr>
                                    <td></td>
                                    <td><input type="submit" name="submit" value="Daftar"/></td>
                                </tr>
                            </table>
                        </form>

                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}